#!/usr/bin/env bash
# build-mirrored.sh — generic image build for mirrored upstream apps.
#
# Reads manifest/*.toml files that contain a [build] section. For each such
# app, if the declared image does not exist locally, clones the mirror repo at
# the pinned ref and runs docker build with the declared args + tag.
#
# Idempotent: an existing image is skipped, so deploys stay fast.
# Intended to be called by scripts/deploy.sh before the compose up step.
#
# Usage:
#   ./scripts/build-mirrored.sh            # build all missing images
#   ./scripts/build-mirrored.sh calino     # build only calino
#
# Dependencies: git, docker, python3 (for TOML parsing + env expansion).
set -euo pipefail
cd "$(dirname "$0")/.."

# Source .env so ${VAR} references in build arg values expand correctly.
# The mirror.sh sibling uses the same pattern.
[[ -f .env ]] && set -a && source .env && set +a

BUILD_DIR=$(mktemp -d)
trap 'rm -rf "$BUILD_DIR"' EXIT

BUILT=0
SKIPPED=0

# Collect the TOML files to process.
toml_files=(manifest/*.toml)
if [[ $# -gt 0 ]]; then
  toml_files=()
  for app in "$@"; do
    toml_files+=("manifest/${app}.toml")
  done
fi

for toml in "${toml_files[@]}"; do
  [[ -f "$toml" ]] || continue

  # Run a single Python process per TOML file. It:
  #   - reads the [app] section for the image name
  #   - reads the [build] section for repo, ref, and build args
  #   - validates that ref is a full 40-char SHA
  #   - expands ${VAR} in arg values from the current environment
  #   - outputs one tab-separated line: image\trepo\tref\targ1\targ2\t...
  #   - exits with code 0 only when a build is needed
  #   - exits with code 2 (no build section) or 3 (empty fields) to skip
  OUTPUT=$(python3 -c "
import sys, tomllib, os, re, string

with open('$toml', 'rb') as f:
    m = tomllib.load(f)

image = m.get('app', {}).get('image', '')
b = m.get('build')
if not b:
    sys.exit(2)          # no [build] section, skip

repo = b.get('repo', '')
ref  = b.get('ref', '')

if not repo or not ref or not image:
    sys.exit(3)          # missing required field, skip

# Require full 40-char commit SHA (operator review blocker 3).
if not re.fullmatch(r'[0-9a-f]{40}', ref):
    print(f'ERROR: [build].ref \"{ref}\" in $toml is not a 40-char hex SHA', file=sys.stderr)
    sys.exit(4)

# Expand ${VAR} references in arg values from the environment
# (operator review blocker 4).  An unset variable raises KeyError
# (hard failure, not silent empty string).
args_line = []
for k, v in b.get('args', {}).items():
    expanded = string.Template(v).substitute(os.environ)
    args_line.append(f'{k}={expanded}')

# Tab-separated output: image\trepo\tref\targ1\targ2\t...
print('\t'.join([image, repo, ref] + args_line))
" 2>&1) || true

  EXIT_CODE=$?
  # Exit code 2 = no [build] section, skip silently.
  if [[ "$EXIT_CODE" -eq 2 ]]; then
    continue
  fi
  # Exit code 3 = missing required field, skip with a note.
  if [[ "$EXIT_CODE" -eq 3 ]]; then
    echo "  build-mirrored: skipping $toml (missing image, repo, or ref)"
    continue
  fi
  # Exit code 4 = invalid ref (message already on stderr).
  if [[ "$EXIT_CODE" -eq 4 ]]; then
    continue
  fi
  # Non-zero for any other reason — show Python's output and abort.
  if [[ "$EXIT_CODE" -ne 0 ]]; then
    echo "$OUTPUT"
    exit "$EXIT_CODE"
  fi

  # Shell-check: the Python output must have at least 3 tab-separated fields.
  printf '%s' "$OUTPUT" | python3 -c "
import sys
line = sys.stdin.read()
parts = line.split('\t')
if len(parts) < 3:
    print('ERROR: malformed build config output', file=sys.stderr)
    sys.exit(1)
" || { echo "$OUTPUT"; exit 1; }

  IFS=$'\t' read -r IMAGE REPO REF ARGS_REST <<<"$OUTPUT"

  echo "  build-mirrored: $IMAGE ($REPO @ $REF)"

  # Idempotent: skip if image already exists.
  if docker image inspect "$IMAGE" >/dev/null 2>&1; then
    echo "    image exists, skipping"
    SKIPPED=$((SKIPPED + 1))
    continue
  fi

  echo "    cloning $REPO @ $REF ..."

  # Operator review blocker 2: git clone --depth 1 --branch <sha> fails for
  # a commit SHA.  Go straight to init + fetch-by-SHA + checkout.
  CLONE_DIR="$BUILD_DIR/$REPO"
  mkdir -p "$CLONE_DIR"
  git init "$CLONE_DIR" >/dev/null 2>&1
  git -C "$CLONE_DIR" remote add origin "https://git.localhost/$REPO.git"
  git -C "$CLONE_DIR" fetch origin "$REF" --depth 1 2>&1 | sed 's/^/    /'
  git -C "$CLONE_DIR" checkout "$REF" 2>&1 | sed 's/^/    /'

  echo "    building $IMAGE ..."

  # Operator review blocker 1: no arrays — ARGS_REST is a (possibly empty)
  # tab-separated string of KEY=VALUE pairs.  Convert tabs to
  # ' --build-arg KEY=VALUE' and pass through eval.  This is safe because
  # the argument strings are generated by our own Python (not user input)
  # and are simple KEY=VALUE pairs that contain spaces only in the value.
  if [[ -n "$ARGS_REST" ]]; then
    ARGS_FLAGS=$(printf ' --build-arg %s' "$ARGS_REST")
    # shellcheck disable=SC2086  # intentional word-splitting for flags
    eval docker build $ARGS_FLAGS -t "$IMAGE" "$CLONE_DIR" 2>&1 | sed 's/^/    /'
  else
    docker build -t "$IMAGE" "$CLONE_DIR" 2>&1 | sed 's/^/    /'
  fi

  echo "    built $IMAGE"
  BUILT=$((BUILT + 1))
done

echo "  build-mirrored: $BUILT built, $SKIPPED skipped"