#!/usr/bin/env bash
# SSO for the admin surfaces: git.<domain> (Forgejo, native OIDC) and
# llm.<domain>/ui (LiteLLM, generic OIDC) both authenticate via Pocket ID —
# one passkey at the door, everywhere. Idempotent; run once per node.
#
#   1. mint OIDC clients "forgejo" + "litellm" in Pocket ID  -> .env
#   2. record the operator's Pocket ID user id (LiteLLM UI admin) -> .env
#   3. [NODE_DOMAIN=localhost only] dev glue: compose override giving
#      containers DNS for *.localhost + trust for Caddy's local CA
#   4. register the auth source in Forgejo; recreate litellm/forgejo/caddy
#
# Break-glass stays: Forgejo local admin password login remains enabled.
set -euo pipefail
cd "$(dirname "$0")/.."
set -a; source .env; set +a

AUTH_URL="https://auth.${NODE_DOMAIN}"
CURL=(/usr/bin/curl -sk -H "X-API-KEY: $POCKET_ID_API_KEY" -H "Content-Type: application/json")
[[ "$NODE_DOMAIN" == "localhost" ]] && CURL+=(--resolve "auth.localhost:443:127.0.0.1")
saveenv() { grep -q "^$1=" .env && sed -i '' "s|^$1=.*|$1=$2|" .env || printf '%s=%s\n' "$1" "$2" >> .env; }

mint_client() {  # mint_client <name> <callback-url> <ENV_PREFIX>
  local name=$1 cb=$2 prefix=$3 id secret
  id=$("${CURL[@]}" "$AUTH_URL/api/oidc/clients" | python3 -c "
import json,sys
for c in json.load(sys.stdin)['data']:
    if c['name']=='$name': print(c['id']); break")
  if [[ -n "$id" && -n "$(eval echo \${${prefix}_CLIENT_SECRET:-})" ]]; then
    echo "   client '$name' exists — skip"
    return
  fi
  if [[ -z "$id" ]]; then
    id=$("${CURL[@]}" -X POST "$AUTH_URL/api/oidc/clients" \
      -d "{\"name\":\"$name\",\"callbackURLs\":[\"$cb\"]}" \
      | python3 -c 'import json,sys; print(json.load(sys.stdin)["id"])')
  fi
  secret=$("${CURL[@]}" -X POST "$AUTH_URL/api/oidc/clients/$id/secret" \
      | python3 -c 'import json,sys; print(json.load(sys.stdin)["secret"])')
  saveenv "${prefix}_CLIENT_ID" "$id"
  saveenv "${prefix}_CLIENT_SECRET" "$secret"
  echo "   minted '$name' ($id) -> .env"
}

echo "== 1/4 OIDC clients in Pocket ID =="
mint_client forgejo "https://git.${NODE_DOMAIN}/user/oauth2/pocket-id/callback" FORGEJO_OIDC
mint_client litellm "https://llm.${NODE_DOMAIN}/sso/callback" LITELLM_OIDC

echo "== 2/4 operator = LiteLLM UI admin =="
ADMIN_ID=$("${CURL[@]}" "$AUTH_URL/api/users" | python3 -c "
import json,sys
users=[u for u in json.load(sys.stdin)['data'] if u.get('isAdmin')]
print(users[0]['id'] if users else '')")
[[ -n "$ADMIN_ID" ]] && saveenv LITELLM_PROXY_ADMIN_ID "$ADMIN_ID" && echo "   admin user id: $ADMIN_ID"

echo "== 3/4 local-dev glue =="
if [[ "$NODE_DOMAIN" == "localhost" ]]; then
  # containers must reach https://auth.localhost (via Caddy) and trust its CA
  docker exec forgejo cat /etc/ssl/certs/ca-certificates.crt > .local-ca-bundle.pem
  docker exec caddy cat /data/caddy/pki/authorities/local/root.crt >> .local-ca-bundle.pem
  [[ -f docker-compose.override.yml ]] || cat > docker-compose.override.yml <<'EOF'
# LOCAL-DEV ONLY (gitignored, generated by sso-setup.sh): with a real domain
# and public CA none of this exists. Gives containers DNS for *.localhost via
# Caddy and trust for Caddy's internal CA (system bundle + local root).
services:
  caddy:
    networks:
      edge:
        aliases: [auth.localhost, git.localhost, llm.localhost]
  forgejo:
    environment:
      SSL_CERT_FILE: /certs/local-bundle.pem
    volumes:
      - ./.local-ca-bundle.pem:/certs/local-bundle.pem:ro
  litellm:
    environment:
      SSL_CERT_FILE: /certs/local-bundle.pem
    volumes:
      - ./.local-ca-bundle.pem:/certs/local-bundle.pem:ro
EOF
  echo "   wrote .local-ca-bundle.pem + docker-compose.override.yml"
else
  echo "   real domain — no glue needed"
fi

echo "== 4/4 apply =="
set -a; source .env; set +a
docker compose up -d caddy forgejo litellm >/dev/null 2>&1
sleep 5
FJ() { docker exec -u 1000 forgejo forgejo "$@"; }
if FJ admin auth list | grep -q pocket-id; then
  echo "   forgejo auth source exists — skip"
else
  FJ admin auth add-oauth --name pocket-id --provider openidConnect \
     --key "$FORGEJO_OIDC_CLIENT_ID" --secret "$FORGEJO_OIDC_CLIENT_SECRET" \
     --auto-discover-url "$AUTH_URL/.well-known/openid-configuration" \
     --scopes "openid profile email"
  echo "   forgejo: pocket-id auth source registered"
fi
echo
echo "Done. git.$NODE_DOMAIN shows 'Sign in with pocket-id';"
echo "llm.$NODE_DOMAIN/ui hands login to Pocket ID. Passkey covers both."
